### ISSUE TITLE
Encountering error when converting to epub

### ISSUE THREAD

**Issue by janamadeleine** [Architrixs/Wattpad2Epub#3]
hello i keep on encountering this when it was converting to epub file. The following below is what appears
 File "C:\Users\Admin\Downloads\Wattpad2Epub\Wattpad2epub.py", line 105, in <module>
    output = pypandoc.convert_file(story_name+".html", 'epub3', outputfile=story_name+".epub", extra_args=['--epub-chapter-level=2', f'--epub-cover-image={cover_image}'])
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\pypandoc\__init__.py", line 150, in convert_file
    return _convert_input(source_file, format, 'path', to, extra_args=extra_args,
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\pypandoc\__init__.py", line 351, in _convert_input
    raise RuntimeError(
RuntimeError: Pandoc died with exitcode "99" during conversion: File Name(had to change for privacy purpose).jpg not found in resource path

**Comment by Architrixs** [comment]
**Hey! 
I'll look into the issue more, but for the time being you can just remove the argument `f'--epub-cover-image={cover_image}'`, from the Wattpad2epub.py file and save.
It will generate a epub, just without a cover image.**

**Comment by janamadeleine** [comment]
> 

thanks! It works now. Hopefully u fix it soon.
