### ISSUE TITLE
TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by skmd0** [Architrixs/Wattpad2Epub#5]
Running `python .\Wattpad2epub.py https://www.wattpad.com/story/315799543-forbidden-love-max-mayfield` produces this traceback:

```
Traceback (most recent call last):
  File "C:\Users\Domen\Downloads\Wattpad2Epub-main\Wattpad2epub.py", line 69, in <module>
    file.write("<br><b>Tags:</b> "+tags+"<br><br>"+summary+"<br>")
TypeError: can only concatenate str (not "NoneType") to str
```

Windows 10, Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] on win32

I tried to install all the dependencies listed with `pip install <dependency name>`, but I am not sure if everything got installed correctly.

**Comment by Architrixs** [comment]
Try the command with the link of a chapter like so `python3 .\Wattpad2epub.py https://www.wattpad.com/1244918405-her-perfect-mistake-max-mayfield-%7Eintroduction%7E`

Hey, Sorry for late reply, happy reading!!
