### ISSUE TITLE
401 Client Error

### ISSUE THREAD

**Issue by lieshac** [Architrixs/Wattpad2Epub#6]
I can't seem to download since this one keep showing up. it always shows "There was a problem: 401 Client Error: Unauthorized for url: https://www.wattpad.com/apiv2/info?id="

**Comment by Architrixs** [comment]
This means the link you are providing, is incorrect.

Try the command with the link of a chapter like so `python3 .\Wattpad2epub.py https://www.wattpad.com/1244918405-her-perfect-mistake-max-mayfield-%7Eintroduction%7E`


happy reading!!

**Comment by lieshac** [comment]
> This means the link you are providing, is incorrect.
> 
> Try the command with the link of a chapter like so `python3 .\Wattpad2epub.py https://www.wattpad.com/1244918405-her-perfect-mistake-max-mayfield-%7Eintroduction%7E`
> 
> happy reading!!

There was a problem: 401 Client Error: Unauthorized for url: https://www.wattpad.com/apiv2/info?id=1244918405
Traceback (most recent call last):
  File "C:\Users\universal\Documents\Wattpad2Epub\Wattpad2epub.py", line 42, in <module>
    tags = res.json()['tags']
KeyError: 'tags' 

i tried the link you provided and still not working though this one keeps showing , hope you can helpthank youuu

**Comment by Architrixs** [comment]
> > This means the link you are providing, is incorrect.
> > Try the command with the link of a chapter like so `python3 .\Wattpad2epub.py https://www.wattpad.com/1244918405-her-perfect-mistake-max-mayfield-%7Eintroduction%7E`
> > happy reading!!
> 
> There was a problem: 401 Client Error: Unauthorized for url: https://www.wattpad.com/apiv2/info?id=1244918405 Traceback (most recent call last): File "C:\Users\universal\Documents\Wattpad2Epub\Wattpad2epub.py", line 42, in tags = res.json()['tags'] KeyError: 'tags'
> 
> i tried the link you provided and still not working though this one keeps showing , hope you can helpthank youuu

Looks like the api endpoints have changed, i'll look for new ones, and update accordingly soon.

**Comment by lieshac** [comment]
> > > This means the link you are providing, is incorrect.
> > > Try the command with the link of a chapter like so `python3 .\Wattpad2epub.py https://www.wattpad.com/1244918405-her-perfect-mistake-max-mayfield-%7Eintroduction%7E`
> > > happy reading!!
> > 
> > 
> > There was a problem: 401 Client Error: Unauthorized for url: https://www.wattpad.com/apiv2/info?id=1244918405 Traceback (most recent call last): File "C:\Users\universal\Documents\Wattpad2Epub\Wattpad2epub.py", line 42, in tags = res.json()['tags'] KeyError: 'tags'
> > i tried the link you provided and still not working though this one keeps showing , hope you can helpthank youuu
> 
> Looks like the api endpoints have changed, i'll look for new ones, and update accordingly soon.

Thank you so much. This code is actually a life saver and really easy to use. Have a great day :D

**Comment by Architrixs** [comment]
It should be working now, Thanks for waiting.
